### ISSUE TITLE
Add rules for categories per country/region to mark a category as closed rather than hiding it

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#291]
**Is your feature request related to a problem? Please describe.**
* When governments decide to open or close specific categories of places, right now the only option we have is to add or remove them from the map.
* However, this may be surprising for users or even frustrating, because they cannot possibly know why the category of shop is closed (not everybody keeps track of the official rules).

**Describe the solution you'd like**
* It would be helpful to mark a category as closed for a country or region.
* Ideally these "region rules" would (optionally?) overwrite the individual taggings.

**Describe alternatives you've considered**
None considered.

**Additional context**
Background: https://github.com/bleibtoffen/caresteouvert-de/issues/30#issuecomment-611952063

**Comment by caugner** [comment]
Actually, this feature could somewhat supersede the definition of categories per country.

Sure, there will always be some degree of customization with regard to adding specific categories (cf. [chemist for DACH](#240)). However it would no longer be necessary to hide any category in any country (expect if that category is *very very* irrelvant), because "closed" categories could simply be "ruled out" (pun intended).

**Comment by PanierAvide** [comment]
This might be done by extending `categories.json`, like having for each category and/or subcategory a property `legalOpeningStatus` with values like `"FR": "open"` or `closed` or `no_visitors` (= possible delivery/takeaway/contact by phone...).

**Comment by PanierAvide** [comment]
This is now supported by `legal_rules.csv` in covid_enseignes : https://github.com/PanierAvide/Covid_enseignes#stores-and-services-legally-allowed-to-open-legal_rulescsv

Only thing left is make this CSV file used by caresteouvert map.

**Comment by PanierAvide** [comment]
Note that this will allow to make ambiguous categories clearer when shown, but displaying all places from closed categories in this file would cause performance issues.

**Comment by georg-d** [comment]
Please consider to 
a) use a base/background layer that shows "all" categories (yea, in reality, it will not be "all" but just "a lot")
and
b) load those closed categories "very lazy" (i.e. after the possibly open POIs and only when capacity exists, maybe only in very high zoom levels) and indicate via icon whether these categories have already been loaded or not yet.

Rationale: Multiple times, I was confused whether I am looking at the right part of the map because I know the position of several Corona-relevant shops only roughly, e.g. https://www.openstreetmap.org/node/3979040669 shop=clothes and https://www.openstreetmap.org/node/370637765 shop=outdoor selling masks and https://www.openstreetmap.org/node/3283156659 craft=tailor selling masks and material for sewing masks at home. Even after verifying the positions, because these shops do not show up at all, I can't provide the information they sell masks - which are hard to get in many parts of Germany despite/because they are now mandatory.

I am aware my examples are void when https://github.com/osmontrouge/caresteouvert/issues/558 is completely implemented but I strongly assume similar issues will happen again and again, because in all the cities/regions/countries together so many rules changes do happen that the website simply can't be always up to date.

**Comment by PanierAvide** [comment]
There is now basic support of `legal_rules.csv` file (see https://github.com/PanierAvide/Covid_enseignes#stores-and-services-legally-allowed-to-open-legal_rulescsv ) to set which categories of POIs are closed per country. Places part of closed categories will appear as closed automatically as now (if category is listed on left sidebar).
